const TileSpacialType = {
    FLOOR: 0,
    LEFT_EDGE_WALL: 1,
    RIGHT_EDGE_WALL: 2,
    TOP_EDGE_WALL: 3,
    BOTTOM_EDGE_WALL: 4,
    TOP_LEFT_CORNER_WALL: 5,
    TOP_RIGHT_CORNER_WALL: 6,
    BOTTOM_LEFT_CORNER_WALL: 7,
    BOTTOM_RIGHT_CORNER_WALL: 8,
    TOP_LEFT_INNER_WALL: 9,
    TOP_RIGHT_INNER_WALL: 10,
    BOTTOM_LEFT_INNER_WALL: 11,
    BOTTOM_RIGHT_INNER_WALL: 12
}

module.exports = TileSpacialType;